export const INDICES = {
  'NIFTY 50': [
    'NSE-RELIANCE','NSE-TCS','NSE-HDFCBANK','NSE-INFY','NSE-ICICIBANK',
    'NSE-HINDUNILVR','NSE-ITC','NSE-SBIN','NSE-BHARTIARTL','NSE-KOTAKBANK',
    'NSE-LT','NSE-AXISBANK','NSE-ASIANPAINT','NSE-MARUTI','NSE-TITAN',
    'NSE-SUNPHARMA','NSE-WIPRO','NSE-HCLTECH','NSE-ULTRACEMCO','NSE-BAJFINANCE',
    'NSE-NESTLEIND','NSE-TECHM','NSE-DIVISLAB','NSE-DRREDDY','NSE-DMART',
    'NSE-POWERGRID','NSE-NTPC','NSE-JSWSTEEL','NSE-TATAMOTORS','NSE-ONGC',
    'NSE-COALINDIA','NSE-ADANIENT','NSE-ADANIPORTS','NSE-BAJAJFINSV','NSE-BRITANNIA',
    'NSE-CIPLA','NSE-EICHERMOT','NSE-GRASIM','NSE-HEROMOTOCO','NSE-HINDALCO',
    'NSE-INDUSINDBK','NSE-LTIM','NSE-MM','NSE-SBILIFE','NSE-SHRIRAMFIN',
    'NSE-TATACONSUM','NSE-TATASTEEL','NSE-TRENT','NSE-APOLLOHOSP','NSE-BAJAJ-AUTO'
  ],
  'NIFTY Bank': [
    'NSE-HDFCBANK','NSE-ICICIBANK','NSE-KOTAKBANK','NSE-SBIN','NSE-AXISBANK',
    'NSE-INDUSINDBK','NSE-BANDHANBNK','NSE-FEDERALBNK','NSE-IDFCFIRSTB','NSE-AUBANK',
    'NSE-PNB','NSE-BANKBARODA'
  ],
  'NIFTY IT': [
    'NSE-TCS','NSE-INFY','NSE-WIPRO','NSE-HCLTECH','NSE-TECHM',
    'NSE-LTIM','NSE-MPHASIS','NSE-COFORGE','NSE-PERSISTENT','NSE-OFSS'
  ],
  'NIFTY Pharma': [
    'NSE-SUNPHARMA','NSE-DIVISLAB','NSE-DRREDDY','NSE-CIPLA','NSE-APOLLOHOSP',
    'NSE-TORNTPHARM','NSE-LUPIN','NSE-ALKEM','NSE-AUROPHARMA','NSE-IPCALAB'
  ],
  'Custom': [],
};
